import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import Navbar from "@/components/navbar/Navbar";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="de">
      <body className={`py-4 pl-4 flex flex-col min-h-[98vh] justify-center ${inter.className} bg-black overflow-hidden`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}


